### ISSUE TITLE
Research - CNN / machine learning?

### ISSUE THREAD

**Issue by apvarghese19** [umigv/MkII#22]
Issue: Need to find the easiest algorithm to use. Something else might be better than a CNN for lane detection. Also we would need to figure out what data to use to train this model.

Task: Create a document for this, collect articles and propose ideas

**Comment by apvarghese19** [comment]
Research about using a GAN network

**Comment by Garadan1** [comment]
Hi @apvarghese19, please confirm if this issue is still relevant for the WN22 term. Thank you!
