### ISSUE TITLE
Code - Remove distortion

### ISSUE THREAD

**Issue by apvarghese19** [umigv/MkII#25]
Task: Start from where we left off from last year and go through tutorial in the cv tasks doc. 
IMPORTANT: When creating the bird-eye view, need to find out how to take advantage of the Zed camera's depth map.
Last years code: https://github.com/umigv/computer_vision/tree/master/cv_2020_2021

**Comment by Garadan1** [comment]
@apvarghese19 Can you confirm that this issue is still in progress
