### ISSUE TITLE
Code - Extract Frames from zed recording

### ISSUE THREAD

**Issue by apvarghese19** [umigv/MkII#26]
Task: Go through cv tasks document and extract zed recording frames using zed documentation

Last years progress: https://github.com/umigv/computer_vision/tree/master/cv_2020_2021

**Comment by Garadan1** [comment]
Hi @mmiracky, can you confirm that this issue is still necessary? If it’s in progress, feel free to move it to the “in progress” pipeline. Thank you!!

**Comment by apvarghese19** [comment]
Files in cv_stack (zed_test, zed_recording) complete this task
