### ISSUE TITLE
Jetson - ROS noetic docker workaround

### ISSUE THREAD

**Issue by apvarghese19** [umigv/MkII#30]
Use docker to run ros noetic on the jetson. Need to figure out how to let docker access the usb zed camera

**Comment by Garadan1** [comment]
Removing old sprints from F21

**Comment by rbharadwaj9** [comment]
Three options are being considered:
1. Docker (difficult and unfamiliar)
2. Building from source (there's documentation but seems to be impossible)
3. Cross compatibility using melodic (running on jetson) and noetic (rest of the processors). This needs messages to be commonly supported between the two platforms.
