### ISSUE TITLE
ROS

### ISSUE THREAD

**Issue by dswelch** [umigv/MkII#65]

**Comment by dswelch** [comment]
Rajiv created a visualizer ROS node to visual ROS topics. Converted ADSDetection to work with ROS. Eventual goal is to be able to have a visualization of our lane detection algorithms for easier debugging.

**Comment by apvarghese19** [comment]
Created a new c++ ros node to handle occupancy grid since c++ would theoretically be faster. Still need to convert code to c++. Hz is at 0.45, goal is to get it at least 10x that.
